name: izmirferry
description: Show ferry schedules in İzmir.
publish_to: 'none'

version: 0.3.4+13

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_loggy: ^2.0.2
  loggy: ^2.0.3
  easy_localization_loader: ^1.0.1+1
  easy_localization: ^3.0.2
  get_it: ^7.6.0
  dio: ^5.1.2
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_file_store: ^1.2.2
  html: ^0.15.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_loggy_dio: ^3.0.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  auto_route: ^7.2.0
  awesome_extensions: ^2.0.7
  collection: ^1.17.0
  shimmer: ^3.0.0
  firebase_core: ^2.13.0
  firebase_crashlytics: ^3.3.1
  firebase_in_app_messaging: ^0.7.3+1
  firebase_analytics: ^10.4.1
  url_launcher: ^6.1.11
  dropdown_button2: ^2.1.3
  chips_choice: ^3.0.0
  flexi_chip: ^1.0.8
  package_info_plus: ^4.0.2
  font_awesome_flutter: ^10.4.0
  scrollable_positioned_list: ^0.3.8
  dio_cache_interceptor_hive_store: ^3.2.1
  path_provider: ^2.0.15
  get_it_future_builder: ^0.3.1
  google_mobile_ads: ^3.0.0
  sqflite: ^2.2.8+4
  tuple: ^2.0.1
  firebase_messaging: ^14.6.2
  lottie: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.4
  json_serializable: ^6.6.2
  http_mock_adapter: ^0.4.4
  auto_route_generator: ^7.1.1
  flutter_launcher_icons: ^0.13.1

flutter:
  assets:
    - assets/translations/
    - assets/icon/
    - assets/locations/
  uses-material-design: true

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
