name: Analyzing

on:
  pull_request:
    branches: [master]
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2

      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter analyze