name: Formatting

on:
  pull_request:
    branches: [master]
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Fetching repo"
        uses: actions/checkout@v3
      - name: "Setting up Flutter SDK"
        uses: subosito/flutter-action@v2

      - name: "Getting dependencies"
        run: flutter pub get
      - name: "Checking code formatting"
        run: dart format --output=none --set-exit-if-changed .