name: Testing

on:
  pull_request:
    branches: [master]
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Fetching repo"
        uses: actions/checkout@v3
      - name: "Setting up Flutter SDK"
        uses: subosito/flutter-action@v2

      - name: "Getting dependencies"
        run: flutter pub get
      - name: "Generating code"
        run: flutter pub run build_runner build
      - name: "Running tests"
        run: flutter test
      - name: "Generating coverage"
        run: flutter test --coverage
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          verbose: true # optional (default = false)